#!/bin/bash
#------------------------------------------------------------------------------
# 
# Automated FreeNX Installation Script
#
# Requires NoMachine Sources: http://www.nomachine.com/sources.php
# 
# Compiler: Nate Mitchell <nathanjamesmitchell@gmail.com>
#
# License ISC License
# 
# Copyright (c) 2013, Nate Mitchell <nathanjamesmitchell@gmail.com>
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
#------------------------------------------------------------------------------

NXPREFIX=/usr/NX
echo "FreeNX Custom Pre-Configuration Script"
echo "..."
echo "..."
echo "..."
echo "Unpacking source tarballs"
for i in $( ls | grep .tar.gz ); do tar zxvf $i && rm -f $i; done
echo "Compiling nx-X11 World"
cd nx-X11
make World
cd ..
echo "Compiling nxproxy"
cd nxproxy
./configure && make
cd ..
echo "Copying NX libraries"
mkdir -p ${NXPREFIX}/lib ${NXPREFIX}/bin
cp -a nx-X11/lib/X11/libX11.so* ${NXPREFIX}/lib
cp -a nx-X11/lib/Xext/libXext.so* ${NXPREFIX}/lib
cp -a nx-X11/lib/Xrender/libXrender.so* ${NXPREFIX}/lib
cp -a nx-X11/lib/Xrender/libXrender.so.1.2.2 ${NXPREFIX}/lib
cp -a nxcomp/libXcomp.so* ${NXPREFIX}/lib
cp -a nxcompext/libXcompext.so* ${NXPREFIX}/lib
cp -a nxcompshad/libXcompshad.so.3.5.0 ${NXPREFIX}/lib/libXcompshad.so.3
echo "Copying NX binaries"
cp -a nx-X11/programs/Xserver/nxagent ${NXPREFIX}/bin
cp -a nxproxy/nxproxy ${NXPREFIX}/bin
echo "Building FreeNX"
cd freenx-server
echo "Compiling nxredir"
cd nxredir
make
cd ..
echo "Compiling nxserver-helper"
cd nxserver-helper
make
cd ..
echo "Compiling nxpasswd"
cd nxviewer-passwd
xmkmf
make World
cd ..
echo "Installing binaries included in FreeNX trunk"
cd nxredir
cp -a libnxredir.so.0 libnxredir.so
make install
cd ..
cp -a nxserver-helper/nxserver-helper ${NXPREFIX}/bin
cp -a nxviewer-passwd/nxpasswd/nxpasswd ${NXPREFIX}/bin
echo "Copying scripts to ${NXPREFIX}/bin"
cp nx* ${NXPREFIX}/bin
echo "Copying node.conf"
cp -a node.conf ${NXPREFIX}/etc/node.conf
read -p "About to copy binaries - this will cause NX to stop working until the installation is complete. Ensure all users are logged out. To continue, press ENTER"
echo "Copying nx binaries to /usr/bin"
cp -a ${NXPREFIX}/bin/nx* /usr/bin/

echo "Pre-configuration complete!"
echo "Run 'nxsetup --install' to complete installation"
echo "..."
echo "Don't forget to change the "EXTERNAL_PROXY_IP" setting in /usr/NX/etc/node.conf"
echo "to this server's IP address"
echo 'i.e. EXTERNAL_PROXY_IP="192.168.0.1"'
